### ISSUE TITLE
Issue regarding PR

### ISSUE THREAD

**Issue by imaaquibali** [Diusburg/LandingPage#4]
hey, 

I send a PR and u guys not merge it. is it have any issue than please tell me i will fix it.

if you guys merge it i will work on animated buttons.

hope you guys response as soon as possible. 🙃

**Comment by Mohasin-Haque** [comment]
hey aaquib, we are reviewing your changes. please have patience untill we review your code.

**Comment by Diusburg** [comment]
please deploy the changes so that we can review it easily

**Comment by Diusburg** [comment]
resolved
